In [1]:
'''
https://scikit-learn.org/stable/modules/neural_networks_supervised.html#classification
https://scikit-learn.org/stable/supervised_learning.html


'''

'\nhttps://scikit-learn.org/stable/modules/neural_networks_supervised.html#classification\nhttps://scikit-learn.org/stable/supervised_learning.html\n\n\n'

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from itertools import cycle


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV

#class
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from dmba import plotDecisionTree

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import PrecisionRecallDisplay

#score
from sklearn.metrics import precision_score, accuracy_score, roc_auc_score, confusion_matrix,f1_score, roc_curve, auc, recall_score

from sklearn.datasets import make_blobs
from sklearn.svm import LinearSVC



In [3]:
def evaluateBinaryClassification(predictions, actuals):
    contigency = pd.crosstab(actuals,predictions)
    TP = contigency[1][1]
    TN = contigency[0][0]
    FP = contigency[1][0]
    FN = contigency[0][1]
    n = contigency.sum().sum()

    Acuracy = (TP + TN)/n
    Recall = TP/(TP+FN)
    Precision = TP/(TP+FP)
    FScore = 2*Recall*Precision/(Recall+Precision)
    
    return Acuracy, Recall, Precision, FScore

#Read data

In [4]:
#Read data
#Read data
df_agg = pd.read_csv("Sample Data/FS_ALL.csv", index_col=0)
df_agg.head()

Short-term debt (% of total external debt)  \
Total debt service (% of exports of goods, serv...                                               
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   

                                                    Real interest rate (%)  \
Total debt service (% of exports of goods, serv...                           
0.0                                                               0.511705   
0.0                                                               0.512088   
0.0                                                               0.511337   
0.0                                                               0.509767   
0.0                                                               0.508391   

                                                    Total reserves minus gold (in %)  \
Total debt service (% of exports of goods, serv...                                     
0.0                                                                         1.000000   
0.0                                                                         0.848367   
0.0                                                                         0.664417   
0.0                                                                         0.472346   
0.0                                                                         0.404584   

                                                    Trade (% of GDP)  \
Total debt service (% of exports of goods, serv...                     
0.0                                                         0.380783   
0.0                                                         0.371018   
0.0                                                         0.338931   
0.0                                                         0.347603   
0.0                                                         0.356862   

                                                    Imports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.0                                                                                    0.002563   
0.0                                                                                    0.003331   
0.0                                                                                    0.004087   
0.0                                                                                    0.006803   
0.0                                                                                    0.008622   

                                                    Exports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.0                                                                                    0.003350   
0.0                                                                                    0.003961   
0.0                                                                                    0.005054   
0.0                                                                                    0.007776   
0.0                                                                                    0.009476   

                                                    Current account balance (% of GDP)  \
Total debt service (% of exports of goods, serv...                                       
0.0                                                                           0.453849   
0.0                                   

#Explore the Data

#Classification with Scikit-Learn

In [5]:
from sklearn import svm

# 讀入資料
X = df_agg.drop(columns=['Target'])
X = X.values
y = df_agg['Target'].values

# 切分訓練與測試資料
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [6]:
print(X,y)

[[0.         0.51170464 1.         ... 0.         0.         1.        ]
 [0.         0.51208846 0.84836691 ... 0.         0.         1.        ]
 [0.         0.51133699 0.66441678 ... 0.         0.         1.        ]
 ...
 [0.69819731 0.57318437 0.04131659 ... 0.76666667 0.33333333 0.05319149]
 [0.76943152 0.63025998 0.0517304  ... 0.86666667 0.33333333 0.05319149]
 [0.73741398 0.5063251  0.04755578 ... 0.96666667 0.33333333 0.05319149]] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1.

In [7]:
# 建立分類器
clf = svm.SVC(kernel='rbf',C=30,gamma='auto')
clf.fit(X_train, y_train)
clf.score(X_test,y_test)

0.9102564102564102

In [8]:
# 預測
y_test_predicted = clf.predict(X_test)
print(y_test_predicted)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [9]:
# 標準答案
y_test

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
# 績效


print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_predicted))
print("Accuracy:", accuracy_score(y_test, y_test_predicted))

print("Precision Score",precision_score(y_test, y_test_predicted, average='macro'))
print("Precision Score (Micro", precision_score(y_test, y_test_predicted, average='micro'))
print("Precision Score (Weighted)",precision_score(y_test, y_test_predicted, average='weighted'))
print("Precision Score", precision_score(y_test, y_test_predicted, average=None))

print("Recall Score (Macro)", recall_score(y_test, y_test_predicted, average='macro',zero_division=1))
print("Recall Score (Micro)", recall_score(y_test, y_test_predicted, average='micro',zero_division=1))
print("Recall Score (Weight)",recall_score(y_test, y_test_predicted, average='weighted',zero_division=1))
print("Recall Score (Avg None)",recall_score(y_test, y_test_predicted, average=None,zero_division=1))


print("Roc_Score:", roc_auc_score(y, clf.decision_function(X)))      
print("F1 Score (Macro):", f1_score(y_test, y_test_predicted, average='macro'))
print("F1 Score (Micro):", f1_score(y_test, y_test_predicted, average='micro'))
print("F1 Score (Weighted):", f1_score(y_test, y_test_predicted, average='weighted'))
print("F1 Score (Avg None):", f1_score(y_test, y_test_predicted, average=None))
print("F1 Score:", f1_score(y_test, y_test_predicted, zero_division=1))

Confusion Matrix:
 [[68  0]
 [ 7  3]]
Accuracy: 0.9102564102564102
Precision Score 0.9533333333333334
Precision Score (Micro 0.9102564102564102
Precision Score (Weighted) 0.9186324786324787
Precision Score [0.90666667 1.        ]
Recall Score (Macro) 0.65
Recall Score (Micro) 0.9102564102564102
Recall Score (Weight) 0.9102564102564102
Recall Score (Avg None) [1.  0.3]
Roc_Score: 0.9311837587699657
F1 Score (Macro): 0.7062937062937062
F1 Score (Micro): 0.9102564102564102
F1 Score (Weighted): 0.8882911959835036
F1 Score (Avg None): [0.95104895 0.46153846]
F1 Score: 0.4615384615384615


Kfold Corss Validation

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear' ,C=10,gamma='auto'), X, y, cv=5)

array([0.82692308, 0.55769231, 0.96153846, 0.32692308, 0.88461538])

In [12]:
cross_val_score(svm.SVC(kernel='rbf' ,C=10,gamma='auto'), X, y, cv=5)

array([0.90384615, 0.61538462, 0.90384615, 0.38461538, 0.88461538])

In [13]:
cross_val_score(svm.SVC(kernel='linear' ,C=20,gamma='auto'), X, y, cv=5)

array([0.75      , 0.57692308, 0.96153846, 0.32692308, 0.88461538])

In [14]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval ,C=cval,gamma='auto'), X, y, cv=5)
        avg_scores[kval+'_'+str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': 0.8884615384615383,
 'rbf_10': 0.7384615384615384,
 'rbf_20': 0.7346153846153846,
 'linear_1': 0.7346153846153846,
 'linear_10': 0.7115384615384616,
 'linear_20': 0.7}

GridSearch CV

In [15]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(X, y)
clf.cv_results_

{'mean_fit_time': array([0.00097699, 0.00097718, 0.00097718, 0.00078173, 0.00097704,
        0.00117259]),
 'std_fit_time': array([7.59953377e-07, 1.90734863e-07, 4.15696997e-07, 3.90863491e-04,
        5.00111031e-07, 3.91102099e-04]),
 'mean_score_time': array([0.00058622, 0.00039086, 0.00039096, 0.00019546, 0.00058637,
        0.00019531]),
 'std_score_time': array([0.00047865, 0.00047871, 0.00047882, 0.00039091, 0.00047877,
        0.00039063]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [16]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000977  7.599534e-07         0.000586        0.000479       1   
1       0.000977  1.907349e-07         0.000391        0.000479       1   
2       0.000977  4.156970e-07         0.000391        0.000479      10   
3       0.000782  3.908635e-04         0.000195        0.000391      10   
4       0.000977  5.001110e-07         0.000586        0.000479      20   
5       0.001173  3.911021e-04         0.000195        0.000391      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.903846   
1       linear   {'C': 1, 'kernel': 'linear'}           0.903846   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.903846   
3       linear  {'C': 10, 'kernel': 'linear'}           0.826923   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.903846   
5       linear  {'C': 20, 'kernel': 'linear'}           0.750000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.884615           0.884615           0.884615           0.884615   
1           0.634615           0.942308           0.307692           0.884615   
2           0.615385           0.903846           0.384615           0.884615   
3           0.557692           0.961538           0.326923           0.884615   
4           0.615385           0.961538           0.307692           0.884615   
5           0.576923           0.961538           0.326923           0.884615   

   mean_test_score  std_test_score  rank_test_score  
0         0.888462        0.007692                1  
1         0.734615        0.239390                3  
2         0.738462        0.208048                2  
3         0.711538        0.235528                5  
4         0.734615        0.244586                3  
5         0.700000        0.227736                6

In [17]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.888462
1       1       linear         0.734615
2      10          rbf         0.738462
3      10       linear         0.711538
4      20          rbf         0.734615
5      20       linear         0.700000

In [18]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs

In [19]:
clf.best_score_

0.8884615384615383

In [20]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

randomizedSearchCV

In [21]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(X, y)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.734615
1       1          rbf         0.888462

Differenct Hyperparameters

In [22]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [23]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X, y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.888462  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.788462        {'n_estimators': 5}
2  logistic_regression    0.853846                   {'C': 1}

In [24]:
#MLP