In [1]:
import pandas as pd

In [2]:
#Read data
df_agg = pd.read_csv("Sample Data/FS_ALL.csv", index_col=0)
df_agg.head()

Short-term debt (% of total external debt)  \
Total debt service (% of exports of goods, serv...                                               
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   
0.0                                                                                        0.0   

                                                    Real interest rate (%)  \
Total debt service (% of exports of goods, serv...                           
0.0                                                               0.511705   
0.0                                                               0.512088   
0.0                                                               0.511337   
0.0                                                               0.509767   
0.0                                                               0.508391   

                                                    Total reserves minus gold (in %)  \
Total debt service (% of exports of goods, serv...                                     
0.0                                                                         1.000000   
0.0                                                                         0.848367   
0.0                                                                         0.664417   
0.0                                                                         0.472346   
0.0                                                                         0.404584   

                                                    Trade (% of GDP)  \
Total debt service (% of exports of goods, serv...                     
0.0                                                         0.380783   
0.0                                                         0.371018   
0.0                                                         0.338931   
0.0                                                         0.347603   
0.0                                                         0.356862   

                                                    Imports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.0                                                                                    0.002563   
0.0                                                                                    0.003331   
0.0                                                                                    0.004087   
0.0                                                                                    0.006803   
0.0                                                                                    0.008622   

                                                    Exports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.0                                                                                    0.003350   
0.0                                                                                    0.003961   
0.0                                                                                    0.005054   
0.0                                                                                    0.007776   
0.0                                                                                    0.009476   

                                                    Current account balance (% of GDP)  \
Total debt service (% of exports of goods, serv...                                       
0.0                                                                           0.453849   
0.0                                   

In [3]:
X = df_agg.drop(columns=['Target'])
y = df_agg['Target']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [5]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [6]:
model.fit(X_train,y_train)

GaussianNB()

In [7]:
model.score(X_test,y_test)

0.6025641025641025

In [8]:
model.predict(X_test)

array([0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 0.])

In [9]:
model.predict_proba(X_test)

array([[1.00000000e+000, 4.30454736e-224],
       [5.31818450e-002, 9.46818155e-001],
       [9.96834164e-001, 3.16583570e-003],
       [1.78720806e-001, 8.21279194e-001],
       [1.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000],
       [9.99976599e-001, 2.34009182e-005],
       [1.00000000e+000, 7.55187925e-250],
       [1.00000000e+000, 2.35936136e-199],
       [1.00000000e+000, 4.61272494e-082],
       [9.06116732e-001, 9.38832676e-002],
       [9.07329077e-003, 9.90926709e-001],
       [9.57889672e-034, 1.00000000e+000],
       [6.56309235e-005, 9.99934369e-001],
       [1.00000000e+000, 1.74606362e-190],
       [1.00000000e+000, 3.85132173e-069],
       [3.40990687e-001, 6.59009313e-001],
       [1.00000000e+000, 2.66126382e-097],
       [6.28676777e-102, 1.00000000e+000],
       [5.50809224e-012, 1.00000000e+000],
       [1.60684265e-001, 8.39315735e-001],
       [1.22068617e-001, 8.77931383e-001],
       [1.00000000e+000, 3.31294938e-059],
       [5.5

In [10]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=10)

array([0.52631579, 0.68421053, 0.88888889, 0.77777778, 0.83333333,
       0.72222222, 0.5       , 0.66666667, 0.83333333, 0.77777778])

In [11]:
from sklearn.model_selection import GridSearchCV
import numpy as np
nb_classifier = GaussianNB()

params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gs_NB = GridSearchCV(estimator=nb_classifier, 
                 param_grid=params_NB, 
                 cv=5,   # use any cross validation technique 
                 verbose=1, 
                 scoring='accuracy') 
gs_NB.fit(X, y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.31...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy', verbose=1)

In [12]:
gs_NB.cv_results_

{'mean_fit_time': array([0.00136809, 0.00156283, 0.001368  , 0.00136809, 0.00117235,
        0.00156341, 0.00136781, 0.00156336, 0.00156322, 0.00136766,
        0.0013679 , 0.00117297, 0.00136862, 0.00136571, 0.00116887,
        0.00136437, 0.00136819, 0.00157118, 0.00156641, 0.00127482,
        0.00156536, 0.00127711, 0.0014708 , 0.001368  , 0.00156622,
        0.00147376, 0.00147128, 0.00138006, 0.00147109, 0.00115981,
        0.00155802, 0.00117254, 0.00136805, 0.00117259, 0.00147095,
        0.00156336, 0.00097752, 0.00156369, 0.00136447, 0.00136461,
        0.00156355, 0.00136642, 0.00097389, 0.00097542, 0.00088544,
        0.00117345, 0.00146971, 0.0013679 , 0.00136781, 0.00156312,
        0.00117269, 0.00156374, 0.00136738, 0.00117254, 0.00136795,
        0.00097742, 0.0015636 , 0.00136809, 0.00156355, 0.00136824,
        0.00097709, 0.00156283, 0.0013679 , 0.00136814, 0.00117245,
        0.00136776, 0.00156317, 0.00136781, 0.00098152, 0.00218239,
        0.00156927, 0.00136819,

In [13]:
gs_NB.best_params_

{'var_smoothing': 0.8111308307896871}

In [14]:
df = pd.DataFrame(gs_NB.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.001368      0.000782         0.001563    4.787859e-04   
1        0.001563      0.000478         0.000978    6.106495e-07   
2        0.001368      0.000479         0.000977    1.784161e-07   
3        0.001368      0.000479         0.000977    3.873843e-07   
4        0.001172      0.000391         0.001173    3.918177e-04   
..            ...           ...              ...             ...   
95       0.000973      0.000007         0.001173    3.911261e-04   
96       0.001365      0.000481         0.001082    2.079729e-04   
97       0.001561      0.000481         0.000980    4.777899e-06   
98       0.001469      0.000437         0.000978    8.971638e-07   
99       0.001563      0.000479         0.000979    4.223711e-06   

   param_var_smoothing                                     params  \
0                  1.0                     {'var_smoothing': 1.0}   
1             0.811131      {'var_smoothing': 0.8111308307896871}   
2             0.657933       {'var_smoothing': 0.657933224657568}   
3              0.53367       {'var_smoothing': 0.533669923120631}   
4             0.432876     {'var_smoothing': 0.43287612810830584}   
..                 ...                                        ...   
95                 0.0   {'var_smoothing': 2.310129700083158e-09}   
96                 0.0   {'var_smoothing': 1.873817422860387e-09}   
97                 0.0   {'var_smoothing': 1.519911082952933e-09}   
98                 0.0  {'var_smoothing': 1.2328467394420635e-09}   
99                 0.0                   {'var_smoothing': 1e-09}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0.903846           0.884615           0.923077   
1            0.903846           0.903846           0.961538   
2            0.903846           0.884615           0.961538   
3            0.903846           0.826923           0.961538   
4            0.903846           0.769231           0.980769   
..                ...                ...                ...   
95           0.923077           0.480769           1.000000   
96           0.923077           0.480769           1.000000   
97           0.923077           0.480769           1.000000   
98           0.923077           0.480769           1.000000   
99           0.923077           0.480769           1.000000   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0            0.826923           0.538462         0.815385        0.142152   
1            0.846154           0.500000         0.823077        0.165608   
2            0.711538           0.480769         0.788462        0.174989   
3            0.519231           0.500000         0.742308        0.194830   
4            0.365385           0.500000         0.703846        0.235402   
..                ...                ...              ...             ...   
95           0.250000           0.519231         0.634615        0.283417   
96           0.250000           0.519231         0.634615        0.283417   
97           0.250000           0.519231         0.634615        0.283417   
98           0.250000           0.519231         0.634615        0.283417   
99           0.250000           0.519231         0.634615        0.283417   

    rank_test_score  
0                 2  
1                 1  
2                 3  
3                 4  
4                 5  
..              ...  
95               15  
96               15  
97               15  
98               15  
99               15  

[100 rows x 14 columns]