In [13]:
import pandas as pd

In [14]:
#Read data
df_mx = pd.read_csv("Sample Data/MX.csv", index_col=0)
df_thai = pd.read_csv("Sample Data/THAI.csv", index_col=0)
df_sgp = pd.read_csv("Sample Data/SGP.csv", index_col=0)

df_agg = pd.concat([df_thai, df_mx, df_sgp])
df_test = pd.concat([df_sgp])
df_agg.head()

Short-term debt (% of total external debt)  \
Total debt service (% of exports of goods, serv...                                               
0.478220                                                                              0.417122   
0.488071                                                                              0.418222   
0.507164                                                                              0.417371   
0.529773                                                                              0.418589   
0.568958                                                                              0.417134   

                                                    Real interest rate (%)  \
Total debt service (% of exports of goods, serv...                           
0.478220                                                          0.395807   
0.488071                                                          0.425714   
0.507164                                                          0.452184   
0.529773                                                          0.497835   
0.568958                                                          0.531526   

                                                    Total reserves minus gold (current US$)  \
Total debt service (% of exports of goods, serv...                                            
0.478220                                                                           0.000143   
0.488071                                                                           0.000000   
0.507164                                                                           0.000707   
0.529773                                                                           0.001689   
0.568958                                                                           0.003913   

                                                    Trade (% of GDP)  \
Total debt service (% of exports of goods, serv...                     
0.478220                                                    0.000000   
0.488071                                                    0.003768   
0.507164                                                    0.028019   
0.529773                                                    0.040052   
0.568958                                                    0.105083   

                                                    Imports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.478220                                                                               0.000000   
0.488071                                                                               0.000047   
0.507164                                                                               0.000663   
0.529773                                                                               0.002715   
0.568958                                                                               0.006484   

                                                    Exports of goods and services (current US$)  \
Total debt service (% of exports of goods, serv...                                                
0.478220                                                                               0.000000   
0.488071                                                                               0.000350   
0.507164                                                                               0.001292   
0.529773                                                                               0.002906   
0.568958                                                                               0.005783   

                                                    Current account balance (% of GDP)  \
Total debt service (% of exports of goods, serv...                                       
0.478220                                                                      0

In [15]:
X = df_agg.drop(columns=['Target'])
y = df_agg['Target']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [17]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [18]:
model.fit(X_train,y_train)

GaussianNB()

In [19]:
model.score(X_test,y_test)

0.7659574468085106

In [20]:
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0])

In [21]:
model.predict_proba(X_test)

array([[9.99999922e-01, 7.82709449e-08],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 5.50930109e-11],
       [8.04162421e-12, 1.00000000e+00],
       [1.00000000e+00, 2.40747229e-19],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.72183092e-10, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [2.78911427e-03, 9.97210886e-01],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 6.76324362e-14],
       [1.00000000e+00, 2.80447421e-11],
       [1.00000000e+00, 6.77869431e-12],
       [1.89001886e-08, 9.99999981e-01],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 8.73070797e-12],
       [9.99975513e-01, 2.44874473e-05],
       [1.489825

In [22]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=10)

array([0.54545455, 0.36363636, 0.54545455, 0.63636364, 0.90909091,
       0.45454545, 0.72727273, 0.54545455, 0.81818182, 0.5       ])

In [25]:
from sklearn.model_selection import GridSearchCV
import numpy as np
nb_classifier = GaussianNB()

params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gs_NB = GridSearchCV(estimator=nb_classifier, 
                 param_grid=params_NB, 
                 cv=5,   # use any cross validation technique 
                 verbose=1, 
                 scoring='accuracy') 
gs_NB.fit(X, y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.31...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy', verbose=1)

In [27]:
gs_NB.cv_results_

{'mean_fit_time': array([0.00413976, 0.00404325, 0.00131249, 0.00113301, 0.00121217,
        0.0009738 , 0.00101409, 0.00100193, 0.00097065, 0.00096641,
        0.00096021, 0.00096307, 0.00096803, 0.00102344, 0.00096908,
        0.00099101, 0.00095978, 0.00221815, 0.00104103, 0.00094662,
        0.00094995, 0.00095515, 0.00095501, 0.00095568, 0.00095425,
        0.0009903 , 0.0009572 , 0.00095372, 0.00095916, 0.00094991,
        0.00095744, 0.00096431, 0.00096164, 0.0009696 , 0.00096803,
        0.00096512, 0.00096273, 0.00096345, 0.00095358, 0.00096259,
        0.00096722, 0.00096245, 0.00096493, 0.00096226, 0.00095844,
        0.00096126, 0.00095897, 0.0009532 , 0.00095596, 0.00095725,
        0.00095987, 0.00095639, 0.00095525, 0.00095606, 0.00095158,
        0.00095735, 0.00095472, 0.00095396, 0.00095997, 0.00095396,
        0.00095496, 0.00095639, 0.00095558, 0.00095892, 0.001054  ,
        0.00125985, 0.00094662, 0.00094199, 0.00094099, 0.00093746,
        0.00093541, 0.00093794,

In [28]:
gs_NB.best_params_

{'var_smoothing': 1.0}

In [30]:
df = pd.DataFrame(gs_NB.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.004140      0.003650         0.001048        0.000320   
1        0.004043      0.005801         0.000950        0.000164   
2        0.001312      0.000117         0.000956        0.000083   
3        0.001133      0.000046         0.000829        0.000024   
4        0.001212      0.000128         0.000858        0.000060   
..            ...           ...              ...             ...   
95       0.000931      0.000005         0.000718        0.000015   
96       0.000935      0.000007         0.000715        0.000006   
97       0.000937      0.000006         0.000714        0.000008   
98       0.000928      0.000004         0.000712        0.000005   
99       0.000924      0.000003         0.000705        0.000001   

   param_var_smoothing                                     params  \
0                  1.0                     {'var_smoothing': 1.0}   
1             0.811131      {'var_smoothing': 0.8111308307896871}   
2             0.657933       {'var_smoothing': 0.657933224657568}   
3              0.53367       {'var_smoothing': 0.533669923120631}   
4             0.432876     {'var_smoothing': 0.43287612810830584}   
..                 ...                                        ...   
95                 0.0   {'var_smoothing': 2.310129700083158e-09}   
96                 0.0   {'var_smoothing': 1.873817422860387e-09}   
97                 0.0   {'var_smoothing': 1.519911082952933e-09}   
98                 0.0  {'var_smoothing': 1.2328467394420635e-09}   
99                 0.0                   {'var_smoothing': 1e-09}   

    split0_test_score  split1_test_score  split2_test_score  \
0              0.8750           0.903226           0.870968   
1              0.8750           0.903226           0.870968   
2              0.8750           0.903226           0.870968   
3              0.8750           0.903226           0.870968   
4              0.8750           0.903226           0.870968   
..                ...                ...                ...   
95             0.0625           0.741935           0.129032   
96             0.0625           0.677419           0.129032   
97             0.0625           0.677419           0.129032   
98             0.0625           0.677419           0.129032   
99             0.0625           0.645161           0.129032   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0            0.870968           0.870968         0.878226        0.012597   
1            0.870968           0.870968         0.878226        0.012597   
2            0.870968           0.870968         0.878226        0.012597   
3            0.870968           0.870968         0.878226        0.012597   
4            0.870968           0.870968         0.878226        0.012597   
..                ...                ...              ...             ...   
95           0.935484           0.903226         0.554435        0.380783   
96           0.935484           0.903226         0.541532        0.375264   
97           0.935484           0.903226         0.541532        0.375264   
98           0.935484           0.903226         0.541532        0.375264   
99           0.935484           0.903226         0.535081        0.373143   

    rank_test_score  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  
..              ...  
95               90  
96               94  
97               94  
98               94  
99               97  

[100 rows x 14 columns]